name: Kenduro deployment

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.FTP_USERNAME }}
        server: ${{ secrets.FTP_SERVER }}
        port: 22
        # port: ${{ secrets.FTP_PORT }}
        local_path: './*'
        remote_path: '/staging.kenduro.com'
        sftp_only: true
        password: ${{ secrets.FTP_PASSWORD }}