on:
  push:
    branches:
    - main
    - dev
    - staging

env:
  APP_PRODUCTION: kenduro.com
  APP_DEV: dev.kenduro.com
  APP_STAGING: staging.kenduro.com

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Set app name
        run: |
          if [ ${{github.ref_name == 'main'}} && ${{github.ref_type == 'branch'}} ]; then
            echo "APP_NAME=$APP_PRODUCTION" >> $GITHUB_ENV
          fi

          if [ ${{github.ref_name == 'dev'}} && ${{github.ref_type == 'branch'}} ]; then
            echo "APP_NAME=$APP_DEV" >> $GITHUB_ENV
          fi

          if [ ${{github.ref_name == 'staging'}} && ${{github.ref_type == 'branch'}} ]; then
            echo "APP_NAME=$APP_STAGING" >> $GITHUB_ENV
          fi

      - name: 📂 Testsss
        run: |
          echo "APP_NAME: $APP_NAME"

      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: './'
      #     server-dir: './${{ env.APP_NAME }}'