on:
  push:
    branches:
    - main
    - dev
    - staging
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Set app name
        run: |
          echo "APP_NAME=${{github.ref_name}}" >> $GITHUB_ENV

          # if [ ${{github.ref_name == 'main'}} && ${{github.ref_type == 'branch'}} ]; then
          #   echo "APP_NAME=kenduro.com" >> $GITHUB_ENV
          # fi

          # if [ ${{github.ref_name == 'dev'}} && ${{github.ref_type == 'branch'}} ]; then
          #   echo "APP_NAME=dev.kenduro.com" >> $GITHUB_ENV
          # fi

          # if [ ${{github.ref_name == 'staging'}} && ${{github.ref_type == 'branch'}} ]; then
          #   echo "APP_NAME=staging.kenduro.com" >> $GITHUB_ENV
          # fi

      - name: 📂 Testsss
        run: |
          echo "APP_NAME: ${{ env.APP_NAME }}"

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './'
          server-dir: './${{ env.APP_NAME }}'